services:
  app:
    image: asidikrdn/simple-rag-api:1.0.0
    container_name: simple-rag-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - API_KEY=your_api_key_here
      - TZ=Asia/Jakarta
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
      - CORS_METHOD=GET,POST,PUT,DELETE
      - CORS_HEADER=Content-Type,Authorization,X-API-Key
      - GEMINI_API_KEY=your_gemini_api_key_here
      - GEMINI_MODEL=gemini-2.0-flash-lite
      - GOOGLE_EMBEDDING_MODEL=your_google_embedding_model_here
      - QDRANT_HOST=http://qdrant:6333
      - QDRANT_API_KEY=your_qdrant_api_key_here
    # Adjust environment variables as needed, or use a .env file
    # Example: To use a .env file, remove the environment block above and add:
    # env_file:
    #   - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
